/**
 * Copyright (c) 2026 hangtiancheng
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

import {
  Framework,
  State,
  createContentGuard,
  registerThemeViews,
  type FrameworkConfig,
} from "@lark.js/docs";

// Auto-generated by defineConfig()
import {
  routes,
  docsConfig,
  loadContent,
  getSearchIndex,
} from "@lark-docs/generated";

// CSS
import "./main.css";

// === Config ===

const config: FrameworkConfig = {
  rootId: "app",
  routeMode: "history",
  routes,
  vdom: false,
  defaultPath: "/",
  // All /docs/* routes map to "theme/docs-layout" (see generated routes).
  // The layout stays mounted across navigation; observeLocation triggers
  // an async render that loads the matching .md content via loadContent.
  defaultView: "theme/docs-layout",
  unmatchedView: "theme/docs-layout",
  error(e: Error) {
    console.error("[lark-docs]", e);
  },
};

// === Register theme views ===
// Pass config so registerThemeViews selects the correct template mode
// (string vs VDOM) based on vdom. Must be called before Framework.boot()
// so views are registered when the default view is mounted during boot.
registerThemeViews({ vdom: config.vdom });

// === Inject site data + content loader into State ===

// Built-in password guard: pages compiled with docsGuardPlugin()
// (frontmatter `protected: true` + DOCS_PASSWORD env) prompt for a
// password; everything else passes through untouched.
const guard = createContentGuard(loadContent);

State.set({ docsConfig, loadContent: guard.loadContent, getSearchIndex });

// === Boot ===

Framework.boot(config);
