/**
 * Copyright (c) 2026 hangtiancheng
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

import { describe, it, expect, beforeEach, afterEach, vi } from "vitest";
import { docsGuardPlugin } from "../src/vite";
import { decryptContent } from "../src/utils/guard";
import fs from "node:fs";
import path from "node:path";
import os from "node:os";

const PASSWORD = "s3cret";

let tmpDir: string;

beforeEach(() => {
  tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "lark-docs-guard-"));
  process.env["DOCS_PASSWORD"] = PASSWORD;
});

afterEach(() => {
  fs.rmSync(tmpDir, { recursive: true, force: true });
  delete process.env["DOCS_PASSWORD"];
});

function writeMd(name: string, content: string): string {
  const filePath = path.join(tmpDir, name);
  fs.writeFileSync(filePath, content, "utf-8");
  return filePath;
}

function compiledModule(html: string, headings: unknown[] = []): string {
  const pageData = {
    title: "Secret Page",
    description: "secret description",
    excerpt: "secret excerpt of the protected body",
    headings,
    relativePath: "secret.md",
  };
  return (
    `// Generated by @lark.js/docs\n` +
    `export const pageData = ${JSON.stringify(pageData, null, 2)};\n\n` +
    `export const contentHtml = ${JSON.stringify(html)};\n`
  );
}

function runTransform(code: string, filePath: string): string | null {
  const plugin = docsGuardPlugin();
  const transform = plugin.transform as unknown as (
    this: { warn: (msg: string) => void },
    code: string,
    id: string,
  ) => { code: string } | null;
  const result = transform.call(
    { warn: () => {} },
    code,
    `${filePath}?lark-docs`,
  );
  return result ? result.code : null;
}

describe("docsGuardPlugin", () => {
  it("encrypts contentHtml and the payload round-trips with decryptContent", async () => {
    const filePath = writeMd(
      "secret.md",
      "---\nprotected: true\n---\n# Secret\n",
    );
    const html = "<h1>Secret</h1><p>classified</p>";
    const headings = [{ level: 2, text: "Secret Heading", slug: "s" }];
    const out = runTransform(compiledModule(html, headings), filePath);

    expect(out).not.toBeNull();
    expect(out!).not.toContain("classified");

    const payloadJson = out!.match(
      /export const contentHtml = ("(?:[^"\\]|\\.)*");/,
    )![1];
    const payload = JSON.parse(JSON.parse(payloadJson));
    expect(payload.encrypted).toBeTypeOf("string");

    // The plaintext is a { html, headings } envelope so the Toc can be
    // restored after unlock.
    const plaintext = await decryptContent(payload, PASSWORD);
    expect(JSON.parse(plaintext)).toEqual({ html, headings });
    await expect(decryptContent(payload, "wrong")).rejects.toThrow();
  });

  it("handles CRLF frontmatter (no silent plaintext bypass)", () => {
    const filePath = writeMd(
      "crlf.md",
      "---\r\nprotected: true\r\n---\r\n# Secret\r\n",
    );
    const out = runTransform(compiledModule("<p>classified</p>"), filePath);
    expect(out).not.toBeNull();
    expect(out!).not.toContain("classified");
  });

  it("catches YAML truthy spellings like `protected: True` (no plaintext bypass)", () => {
    const filePath = writeMd(
      "yaml-true.md",
      "---\nprotected: True\n---\n# Secret\n",
    );
    const out = runTransform(compiledModule("<p>classified</p>"), filePath);
    expect(out).not.toBeNull();
    expect(out!).not.toContain("classified");
  });

  it("does not encrypt when protected is a non-true value", () => {
    const filePath = writeMd(
      "not-protected.md",
      '---\nprotected: "truest"\n---\n# Plain\n',
    );
    const out = runTransform(compiledModule("<p>public</p>"), filePath);
    expect(out).toBeNull();
  });

  it("scrubs excerpt/description/headings from pageData", () => {
    const filePath = writeMd(
      "secret.md",
      "---\nprotected: true\n---\n# Secret\n",
    );
    const out = runTransform(
      compiledModule("<p>x</p>", [
        { level: 2, text: "Secret Heading", slug: "s" },
      ]),
      filePath,
    );

    expect(out).not.toBeNull();
    expect(out!).not.toContain("secret excerpt");
    expect(out!).not.toContain("secret description");
    expect(out!).not.toContain("Secret Heading");
    // Title survives for sidebar display.
    expect(out!).toContain("Secret Page");
  });

  it("restores contentHtml and headings after unlock (cached password)", async () => {
    const filePath = writeMd(
      "secret.md",
      "---\nprotected: true\n---\n# Secret\n",
    );
    const html = '<h2 id="s">Secret Heading</h2>';
    const headings = [{ level: 2, text: "Secret Heading", slug: "s" }];
    const out = runTransform(compiledModule(html, headings), filePath)!;

    const contentHtml = JSON.parse(
      out.match(/export const contentHtml = ("(?:[^"\\]|\\.)*");/)![1],
    ) as string;
    const pageData = JSON.parse(
      out.match(/export const pageData = (\{[\s\S]*?\n\});/)![1],
    ) as Record<string, unknown>;
    expect(pageData["headings"]).toEqual([]);

    const store = new Map([["docs-guard-pwd", PASSWORD]]);
    vi.stubGlobal("sessionStorage", {
      getItem: (k: string) => store.get(k) ?? null,
      setItem: (k: string, v: string) => void store.set(k, v),
      removeItem: (k: string) => void store.delete(k),
    });
    try {
      const { createContentGuard } = await import("../src/theme/docs-guard");
      const guard = createContentGuard(async () => ({
        pageData,
        contentHtml,
      }));
      const result = await guard.loadContent("/secret");
      expect(result!.contentHtml).toBe(html);
      expect(result!.pageData!["headings"]).toEqual(headings);
    } finally {
      vi.unstubAllGlobals();
    }
  });

  it("leaves unprotected pages untouched", () => {
    const filePath = writeMd("plain.md", "---\ntitle: Plain\n---\n# Plain\n");
    const out = runTransform(compiledModule("<p>public</p>"), filePath);
    expect(out).toBeNull();
  });

  it("is a warn-only no-op without DOCS_PASSWORD", () => {
    delete process.env["DOCS_PASSWORD"];
    const filePath = writeMd(
      "secret.md",
      "---\nprotected: true\n---\n# Secret\n",
    );
    const warnSpy = vi.spyOn(console, "warn").mockImplementation(() => {});
    try {
      const out = runTransform(compiledModule("<p>classified</p>"), filePath);
      expect(out).toBeNull();
      // The warning is the whole point of this branch — shipping a
      // protected page unencrypted must never be silent.
      expect(warnSpy).toHaveBeenCalledWith(
        expect.stringContaining("UNENCRYPTED"),
      );
      expect(warnSpy).toHaveBeenCalledWith(expect.stringContaining(filePath));
    } finally {
      warnSpy.mockRestore();
    }
  });
});
